language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker images
  
script: docker run -t  --entrypoint="/bin/sh" -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6 -c "apk add --update --no-cache openssl-dev make build-base && zef install --deps-only . && zef test ."
